default_agent: hosted_agent_kjr92
agents:
  hosted_agent_kjr92:
    name: hosted_agent_kjr92
    language: python
    node_version: '20'
    entrypoint: /Users/tybennett/Developer/ai/custom_agents_workshop/agent_core_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/tybennett/Developer/ai/custom_agents_workshop
    aws:
      execution_role: arn:aws:iam::970547346077:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole-p2t1r
      execution_role_auto_create: true
      account: '970547346077'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://uofsc-awscc-strands-agent-workshop-assignments/assignments
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: hosted_agent_kjr92-Kun03pBunM
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:970547346077:runtime/hosted_agent_kjr92-Kun03pBunM
      agent_session_id: d486a1de-ea2e-47c1-bd85-c7090fc77842
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: hosted_agent_kjr92_mem-ZMfBceCqRh
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:970547346077:memory/hosted_agent_kjr92_mem-ZMfBceCqRh
      memory_name: hosted_agent_kjr92_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
